### ISSUE TITLE
Add support for incoming webhooks

### ISSUE THREAD

**Issue by jneeven** [jneeven/snaketalk#1]
The bot should host a server (e.g. flask) that can catch incoming webhooks from external (non-mattermost websites) and process them accordingly.

**Comment by ttuffin** [comment]
Hi @jneeven,

I'm interested in looking into this one. What would be the advantage of having the bot run a server that catches webhooks as opposed to webhooks being sent from external websites/apps directly to Mattermost itself? One downside I can see to having the bot opening up a listening service is that it adds another possible attack vector. Perhaps you can provide some use-cases so I can understand the idea a little better?

**Comment by jneeven** [comment]
@ttuffin awesome! One use-case of this would be dialog boxes, which need some kind of web adress for mattermost to send requests to (see https://github.com/attzonko/mmpy_bot/issues/138#issuecomment-761635192). Personally, my main use-case would be intercepting webhooks and applying some filters. For example, the GitHub bot sends very annoying dependabot PR notifications that I would like to either format differently or filter out completely. I would also like to be able to buffer certain incoming webhooks over e.g. a minute so that I can later send out a single message to the relevant user rather than flooding some channel with hundreds of webhook messages for frequent events.

I was thinking we could use [aiohttp](https://docs.aiohttp.org/en/stable/web_quickstart.html#variable-resources) for this server, since we need only extremely basic functionality. It would simply use the endpoint name as a webhook ID and pass it on to the bot. The server event loop could then run on a dedicated thread or a dedicated process.
I agree on the security part, and have been trying to figure out exactly how risky this would be, but without much success. I assume that if we set up this "server" to not even send any kind of response (or at the very least it shouldn't serve any files), it should be very hard to expose anything to any kind of attack other than DOS, which seems fine to me. However, I'm not very experienced with web development or security, so I may be wrong. In any case, I'm open to suggestions!

**Comment by ttuffin** [comment]
@jneeven thanks for the explanation, it does sound like it would bring a bunch more functionality to the bot. In regards to the security, I agree that the risk is small as long as we are not serving any content. aiohttp sounds like the logical choice as well, since you already have async heavily integrated into the bot and it should provide everything we need.

I hope to start putting something basic together soon to get the ball rolling.

**Comment by ttuffin** [comment]
Hi @jneeven, finally had some time to do some work on this tonight. Got a webhook server running via aiohttp and an example webhook plugin to go with it. Still quite a bit to do, but I'll submit a PR this weekend so we can make sure it's heading in the right direction.
